### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpfit#29]
Set up CI just like in gpkit.

GitHub is currently advertising a lot of CI integrations: https://github.com/integrations/feature/code. @galbramc, any thoughts on whether those are worth looking in to, or is another Jenkins setup our best bet?

**Comment by galbramc** [comment]
your call. should only take a couple of minutes to get things setup with our jenkins, or you can use one that github provides. We have complete control over ours, no idea what they provide.

**Comment by galbramc** [comment]
Another thing to consider is any dependencies you have. I don't know what machines they are providing for the CI testing, or what means you have to install your dependencies.

Let me know what you want me to do. I just need to know how to run your test (which I assume is the same as gpkit), and what dependencies you have for gpfit.

**Comment by whoburg** [comment]
Well, I started looking into TravisCI just so we could see another CI setupo, but quickly learned that "Python builds are not available on the OSX environment." That's enough to make me uncomfortable with Travis as a CI solution for our Python project.

Therefore, @galbramc if you could help us get set up on jenkins we'd really appreciate it. Dependencies for gpfit are:
 - numpy
 - gpkit

**Comment by galbramc** [comment]
I presume you want both pull request and push configurations just like you have with gpkit. I also presume you want me to use the master branch of gpkit as the dependency?

**Comment by whoburg** [comment]
correct, and correct.

probably don't need to test for multiple solvers -- the part of gpkit that gpfit uses doesn't involve solvers.

**Comment by galbramc** [comment]
ok, so do I need to build gpkit, or can I just add the gpkit to the python path?

**Comment by whoburg** [comment]
I'm not sure --

We definitely want to be testing gpfit against a current version of gpkit, such as that installed by `pip install gpkit`. Would the "add the gpkit to the python path" solution automatically keep gpkit up to date at the resolution of our PyPI releases?

**Comment by galbramc** [comment]
Ok, how about I create a virtualenv were I install gpkit every time we run the tests. That way you always have what you get with pip. Sound good?

Also, could you add from .run_tests import run to __init__.py in gpfit/tests just for consistency?

**Comment by whoburg** [comment]
sounds great.

Just did so in #32. Do you need that change on master or should I leave that branch open as the first test of jenkins/CI?

**Comment by galbramc** [comment]
Sure leave it open as the first test so I can get the script sorted out

**Comment by galbramc** [comment]
Do you want pylint? If so, you should probably add the pylint.cfg file from gpkit and grab the code from run() in run_tests.py

**Comment by galbramc** [comment]
You also need to give acdl-jenkins the same privlages to gpfit as it has for gpkit before I can test

**Comment by whoburg** [comment]
- [x] ok, I gave acdl-jenkins access
 - [ ] by grab the code in run_tests, I assume you mean the xmloutput stuff. I'll do that now.
 - [ ] I want pylint and will copy over the config file, but I'm confused / have a question. I don't actually see pylint warnings over at gpkit, even though I know we have lots of them. Can you re-educate us on how to see how we're doing on pylint?

**Comment by galbramc** [comment]
hmmm, still getting this error:
Couldn't create web hook for repository hoburg/gpfit. Does the user (from global configuration) have admin rights to the repository?

Let me check the pylint stuff

**Comment by whoburg** [comment]
nope, has write access, which is the same setting as gpkit. Does it need admin access?

**Comment by galbramc** [comment]
Yeah I think it needs admin access...

**Comment by galbramc** [comment]
Same goes for gpkit, I have seen some complaints about gpkit as well, and this might explain why

**Comment by galbramc** [comment]
Here is what is going on with pylint:

https://acdl.mit.edu/csi/job/gpkit_PullRequest/658/buildnode=reynolds,optimizer=mosek/violations/

You currently have 728 violation, however the jenkins default configuration was to allow 999 violations, so this is why you have not gotten any failed builds from pylint.

I can lower the number, but you probably need to start an initiative to become pylint compliant. Presumably it will be easier to get gpfit compliant as it appears to be smaller at the moment.

**Comment by galbramc** [comment]
We could gradually lower the threshold so you don't have to fix all problems at once

**Comment by galbramc** [comment]
I'm around all day today if you want to get this wrapped up. We should also talk about the pylint configuration

**Comment by whoburg** [comment]
coming over now

**Comment by galbramc** [comment]
add .pylintrc and pylint.sh to the repo and then I think you can close this issue

(don't forget about test/pylint.cfg)
