### ISSUE TITLE
generate example output automatically

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpfit#30]
just like in gpkit, as discussed here: https://github.com/hoburg/gpfit/pull/26/files#r51971484

@bqpd: which code in gpkit makes this happen?

**Comment by bqpd** [comment]
Oh, we don't have any automatic output consistency testing. All the value checks were hand-coded.

...or do you mean the .txt files in the examples folder? Those are created by the `StdoutCaptured` class in `tests/t_examples.py`

**Comment by whoburg** [comment]
I meant the .txt files. I see what happened -- they're going to the gpkit examples folder. I'll make some changes to gpkit.tests to allow us to specify the right folder.
