### ISSUE TITLE
All terms in multi-term SMA fits have very similar coefficients and exponents

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpfit#45]
This could just be the models I'm fitting to, but it seems like I every time I try to use SMA fits with multiple (K) terms, the result is a sum of K nearly identical terms, e.g. `w**0.149 = 1.2 * (u_1)**0.0106 + 1.22 * (u_1)**0.0105`. This has been my experience with a wide variety of relationship types, and it seems dubious.

**Comment by whoburg** [comment]
This is the behavior I would expect if the data being fitted were nearly log log concave (because in that case, the best possible convex fit for any number of terms would be a single affine plane). Is that possibly the case here?

**Comment by pgkirsch** [comment]
Yes I realized that was probably the case shortly after and forgot to comment/close this. I have often tried to fit slightly log-concave models using GPfit as a way of handling these sorts of relationships. Nothing really to be done here so I will close this issue.
