### ISSUE TITLE
plot_fit function

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpfit#46]
I think GPfit would benefit from a `plot_fit` method for 1D, and perhaps 2D, functions. This method should plot both the original data and the fitted function, and have the option of plotting in log space too.

**Comment by whoburg** [comment]
Yes!

hey @aechevarria1, want to try getting your hands dirty with gpfit?

**Comment by bqpd** [comment]
Seems to have existed since November at https://github.com/hoburg/gpfit/blob/master/gpfit/plot_fit.py
