### ISSUE TITLE
printed solution significantly different from posynomial inequality

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpfit#55]
I think that significant figures on the auto printed fit equation and the posynomial output equation should be the same. 

This is what I see when I run `fit`:
```python
In [4]: fit(X,Y, 4, "SMA")
w**3.72 = 6.35e+10 * (u_1)**-0.243 * (u_2)**-3.43
    + 0.0247 * (u_1)**2.49 * (u_2)**-1.11
    + 2.03e-07 * (u_1)**12.7 * (u_2)**-0.338
    + 6.49e-06 * (u_1)**-1.9 * (u_2)**-0.681
Out[4]: 
(gpkit.PosynomialInequality(w**3.7 >= 0.0247*u_1**2.5*u_2**-1.1 + 2.03e-07*u_1**13*u_2**-0.34
+ 6.35e+10*u_1**-0.24*u_2**-3.4 + 6.49e-06*u_1**-1.9*u_2**-0.68),
 0.0048930297487385886)
```

The difference in significant figures from the printed solution and the `gpkit.PosynomialInequality`resulted in pretty drastic gaps when I compared the fits to the actual data.  `jh01polarfit.pdf` uses all the significant figures, `jh01polarfit1.pdf` uses the posynomial equation.  
[jh01polarfit.pdf](https://github.com/hoburg/gpfit/files/586012/jh01polarfit.pdf)
[jh01polarfit1.pdf](https://github.com/hoburg/gpfit/files/586014/jh01polarfit1.pdf)

**Comment by bqpd** [comment]
@mjburton11, I think this you fixed this, right?
